list1 = ['apple','banana','mango','grapes']
print("first fruit: ", list[0])
print("first fruit: ", list[-1])
print("Orignal list :", list1)
print("length of list is : ", len(list1))
list1.append('guava')
print("updated list:", list1)
list1.remove('apple')
print("updated list:", list1)
list1.sort()
print("new sorted list is :", list1)
list1.pop(1)
print("new list is :", list1)
print("multiplication of list", list1*2)